### ISSUE TITLE
Migrate from community to official providers

### ISSUE THREAD

**Issue by plumbis** [upbound/docs#18]
We need a doc on how to migrate clusters running on community providers can migrate to official providers.

https://github.com/upbound/product/issues/181

**Comment by elohmrow** [comment]
@plumbis we're in the process of the first customer migration from CP --> OP now. If it helps, [here are some notes](https://docs.google.com/document/d/1BQT0uCvEfeRa0ygja8Y8M9cEPt9Aq2j6caBfUrBSQpU/edit?usp=sharing). 

The skeleton for a customer success playbook for this lives in [Notion here](https://www.notion.so/upbound/CP-to-OP-a3ade342d9a04436ae92675d143587c2). Part of the plan is to flesh this out into a known, repeatable, scalable process.

**Comment by plumbis** [comment]
@ezgidemirel wrote a guide here:
https://github.com/upbound/official-providers/blob/main/docs/manual-migration-guide-to-op.md

**Comment by plumbis** [comment]
Guide is live. https://docs-git-fork-plumbis-aws-provider-upboundio.vercel.app/providers/migration/
