### ISSUE TITLE
Mobile anchors don't jump properly 

### ISSUE THREAD

**Issue by plumbis** [upbound/docs#185]
### What's Wrong?

When clicking on an anchor link the page jumps too far and clips the heading. 

![Screenshot_20230725-213017.png](https://github.com/upbound/docs/assets/10537576/dc39a59a-916e-4c24-94ed-32eb0046e353)

**Comment by tr0njavolta** [comment]
![2023-12-19_10-06-26 (1)](https://github.com/upbound/docs/assets/8883519/dfeccf12-915b-44bd-bd69-f6a75b13f6e3)


I'm not seeing this behavior any more.
