### ISSUE TITLE
concept page is blank

### ISSUE THREAD

**Issue by haarchri** [upbound/docs#250]
### URL

https://docs.upbound.io/quickstart/aws-deploy/#next-steps
concept link page is blank

### What's Wrong?

I noticed this page is blank https://docs.upbound.io/concepts.  It is linked from a quickstart/aws-deploy page

**Comment by plumbis** [comment]
Notion issue:
https://www.notion.so/upbound/Get-root-pages-for-all-folders-96d76d7438244e56ad1b5b5f74c4e394?pvs=4
