### ISSUE TITLE
GCP Identity Provider configuration requires project number

### ISSUE THREAD

**Issue by goodemk** [upbound/docs#264]
### URL

https://docs.upbound.io/quickstart/gcp-deploy/#finish-configuring-the-upbound-identity-provider

### What's Wrong?

The fields listed in the spec and in the console are now `ProviderID`, `ServiceAccount` and `ProjectID` and should be updated in the doc and associated screenshot for accuracy. 

Additionally, the Identity Provider format (`ProviderID`) must use the GCP project **number** (e.g. 112233445566) , not the `GCP Project ID` as listed in the examples. In this case the existing screenshot is actually correct.

**Comment by tr0njavolta** [comment]
Thanks for reporting! 

Just to clarify:

`projects/<GCP_PROJECT_ID>/locations/global/workloadIdentityPools/<OIDC_POOL_NAME>/providers/<OIDC_POOL_PROVIDER_NAME>` should be `projects/<GCP_PROJECT_NUMBER>/locations/global/workloadIdentityPools/<OIDC_POOL_NAME>/providers/<OIDC_POOL_PROVIDER_NAME>` The other customer filled fields stay the same here.

And the screenshot `gcp-oidc-finalize.png` needs to be updated to reflect the new required fields. Do these fields need updating in text anywhere else that you can catch? My quick scan says no, but just double checking.

**Comment by tr0njavolta** [comment]
Merged #265 with updated strings
