### ISSUE TITLE
Tables in dark mode are unreadable

### ISSUE THREAD

**Issue by jahabibi** [upbound/docs#285]
### URL
Example URLs:
https://docs.crossplane.io/latest/concepts/managed-resources/#managementpolicies
https://docs.crossplane.io/latest/concepts/patch-and-transform/

### What's Wrong?
When reading docs in dark mode the tables do not properly handle the transition resulting in missing information until you hover over a row and/or when the mouse is hovering the row becomes unreadable.

Sample Screenshots:
![image](https://github.com/upbound/docs/assets/33559523/0aff50f2-5a3e-43a4-b2ee-f19e0d649d58)
![image](https://github.com/upbound/docs/assets/33559523/f3134019-0412-4e91-ad5e-f7ff30210f75)

**Comment by tr0njavolta** [comment]
Thanks for reporting, I've added a PR in the Crossplane docs repo with a quick fix for legibility.
