### ISSUE TITLE
Add docs on Provider Azure client certification auth support

### ISSUE THREAD

**Issue by plumbis** [upbound/docs#287]
https://github.com/upbound/provider-azure/commit/6aeeb7a4cbb3ff8aba50552db4e1a061623f06ff

Provider-Azure added support for using client certs for service providers in 0.40.0. 

We need to add this to azure auth docs.

**Comment by jeanduplessis** [comment]
https://github.com/upbound/docs/pull/280 ?

**Comment by plumbis** [comment]
🤦‍♂️

The request I got for this made me think the docs weren't already written. Closing as a dup.
