### ISSUE TITLE
postgres engineVersion in docs is out of date

### ISSUE THREAD

**Issue by jbw976** [upbound/docs#45]
### What happened?
@jastang updated the Postgres engineVersion field inside the getting started package with https://github.com/upbound/universal-crossplane/issues/238.

However, we missed also updating the content of the docs that has this value too.  The docs page is below, search the page for `engineVersion`:
https://cloud.upbound.io/docs/uxp/build-configuration/#define-a-composite-resource

It should match what's in https://github.com/upbound/universal-crossplane/blob/main/docs/getting-started/configuration/composition.yaml#L139.

**Comment by plumbis** [comment]
This doc no longer exists. Closing.
