### ISSUE TITLE
Integration with Helm

### ISSUE THREAD

**Issue by plumbis** [upbound/docs#59]

**Comment by stevendborrelli** [comment]
This is a dup of an issue in the old repo https://github.com/upbound/upbound-docs/issues/233.

**Comment by stevendborrelli** [comment]
I have a Gist for some of the commands: https://gist.github.com/stevendborrelli/f300ee8a146f75be5988c17c86edfe58, I would be happy to assist in getting this section into the docs.

**Comment by stevendborrelli** [comment]
Yuri also pointed out the docs at https://github.com/upbound/universal-crossplane#installation-with-helm-3
