### ISSUE TITLE
Building and Publishing Packages

### ISSUE THREAD

**Issue by plumbis** [upbound/docs#80]
What problem are you facing?
The [current docs](https://docs.upbound.io/) don't explain on how to build and publish packages. This is a critical piece of the Act-1 experience and the [Marketplace GA announcement](https://docs.google.com/document/d/1ts1L4s6rD--A8cdAvm_OjZ3RyWRvniBYkrRsd9p0oG4/edit).

How could Upbound help solve your problem?
Document on how a user can document, build, push and publish a package from the CLI

See also old docs:

https://github.com/upbound/upbound-docs/blob/master/src/content/upbound-marketplace/publishing-a-listing.md
https://github.com/upbound/upbound-docs/blob/master/src/content/uxp/build-configuration.md

**Comment by plumbis** [comment]
Initial draft available in [docs staging](https://staging.djrzztn8rlazd.amplifyapp.com/)
"Building Packages" needs more coverage. 

Main changes worth initial review

* [Creating and publishing packages](https://staging.djrzztn8rlazd.amplifyapp.com/upbound-marketplace/packages/)
* [up xpkg command reference](https://staging.djrzztn8rlazd.amplifyapp.com/cli/command-reference/xpkg/)
* [Crossplane packages](https://staging.djrzztn8rlazd.amplifyapp.com/uxp/crossplane-concepts/packages/)

Keeping this issue open until the "build packages" section has more content.  

@luebken you are welcome to share the staging links with customers, I'll push to main in the next 24-48 hours when I finish the build content.

/cc @hasheddan

**Comment by luebken** [comment]
Some notes: 
* I used "pushing" packages instead of "publishing". When I say "publish" I refer to make them publicly available.
* We should explain on how to reach out to us for making packages public.
* An end-to-end flow for someone new publishing a package would be: 

  1. `Create personal account` (with a nice name)
  2. `Author/Adapt Package Config` with the right annotations
  3. `Build package`
  4. `Push package`
  5. `Publish package` by contacting us

**Comment by plumbis** [comment]
What's the contact info we want to use for making packages public? What information do they need to provide us?

**Comment by luebken** [comment]
Contact: support@upbound.io and #upbound https://slack.crossplane.io/
Information needed: Github repo, Upbound account, Upbound repo

**Comment by plumbis** [comment]
A very large new draft is available in staging. 
https://staging.djrzztn8rlazd.amplifyapp.com/

Some of the biggest changes:
* New page on [Organizations](https://staging.djrzztn8rlazd.amplifyapp.com/users/organizations/)
* Some updates to [Crossplane Packags](https://staging.djrzztn8rlazd.amplifyapp.com/uxp/crossplane-concepts/packages/)
* Updates to all [xpkg commands in the command ref](https://staging.djrzztn8rlazd.amplifyapp.com/cli/command-reference/xpkg/)
* Major updates to [Creating and Pushing Packages](https://staging.djrzztn8rlazd.amplifyapp.com/upbound-marketplace/packages/)
* New page on [Authentication](https://staging.djrzztn8rlazd.amplifyapp.com/upbound-marketplace/authentication/) with the marketplace covering `up login` and image pull secrets.

The full diff from the current docs can be seen here: https://github.com/upbound/docs/compare/main...staging

Issuing feedback in a PR is going to be nearly unreadable. I would recommend reading using the "Display the source blob" button to get line numbers

![Screen Shot 2022-09-28 at 4 57 28 PM](https://user-images.githubusercontent.com/10537576/192887495-bf1dec2a-5c6e-4427-9cdb-3c348a558205.png)

From there you can click and link directly to a line number.
![Screen Shot 2022-09-28 at 4 57 40 PM](https://user-images.githubusercontent.com/10537576/192887596-ecb98448-21dc-49c2-92d5-f6cbc6c7d8ea.png)

I still need to document the package specs, but this should be a decent starting point for users.

**Comment by plumbis** [comment]
Pushing to prod and marking as completed for now. Feedback welcome whenever.
