### ISSUE TITLE
Not obvious I need an Upbound account when looking at OP docs page

### ISSUE THREAD

**Issue by grantgumina** [upbound/docs#84]
**URL**
[](https://docs.upbound.io/upbound-marketplace/authentication/)

**Problem**
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/372681/191158466-ded2920c-b7ad-41c6-8cc6-fb4525234630.png">

I found it easy to miss the fact that I needed a paid Upbound account to get started with this documentation.

**Suggested Fix**
I'd place the alert box at the top of the page so people like me skimming the docs don't miss it.

**Comment by plumbis** [comment]
Fixed as part of auth chapter rewrite in #80. Available in [staging](https://staging.djrzztn8rlazd.amplifyapp.com/upbound-marketplace/authentication/) now.
