### ISSUE TITLE
Spacing issue on OP page

### ISSUE THREAD

**Issue by grantgumina** [upbound/docs#85]
**URL**

https://docs.upbound.io/upbound-marketplace/authentication/

**Problem**
<img width="534" alt="image" src="https://user-images.githubusercontent.com/372681/191158720-6b8d4de9-0eef-4672-b923-c06313de2974.png">

`Log in with the Up command-line` looks crowded

**Suggested Fix**
Fix spacing to be more like the `Create an Upbound robot account` header.

**Comment by plumbis** [comment]
Fixed with https://github.com/upbound/docs/commit/e61da2bb7654fb73ff7a0deb9e95e6cbffce1278
